import { GDTSymbolItem } from '../types/gdt';

export const GDT_SYMBOLS: GDTSymbolItem[] = [
  // 1. 形状公差 (Form Tolerances) - 4种，无需基准
  {
    id: 'straightness',
    nameZh: '直线度',
    nameEn: 'Straightness',
    category: 'form',
    categoryZh: '形状公差',
    symbol: '―',
    datumRequirement: '无需基准',
    toleranceZone: '两平行直线、两平行平面、或圆柱面之间的区域',
    definition: '限制实际直线对理想直线变动量的一项指标。用于控制零件上的直线要素（如棱线、素线或轴线）的平直程度。',
    application: '导轨滑轨导向面母线、长轴芯棒轴心线、液压活塞杆外壁母线。',
    iconPath: 'straightness',
  },
  {
    id: 'flatness',
    nameZh: '平面度',
    nameEn: 'Flatness',
    category: 'form',
    categoryZh: '形状公差',
    symbol: '⏢',
    datumRequirement: '无需基准',
    toleranceZone: '距离为公差值 t 的两平行平面之间的区域',
    definition: '限制实际平面对理想平面变动量的一项指标。控制表面上所有点落在两平行平面公差带内的平整程度。',
    application: '箱体结合结合面、法兰密封端面、机床工作台安装基面。',
    iconPath: 'flatness',
  },
  {
    id: 'circularity',
    nameZh: '圆度',
    nameEn: 'Circularity / Roundness',
    category: 'form',
    categoryZh: '形状公差',
    symbol: '○',
    datumRequirement: '无需基准',
    toleranceZone: '同一正截面上，半径差为公差值 t 的两同心圆之间的区域',
    definition: '限制实际圆对理想圆变动量的一项指标。控制回转体各垂直横截面边界轮廓的圆整度，防止椭圆或多棱棱度。',
    application: '轴承轴颈、滚珠滚道表面、气缸内孔截面、高压阀门密封阀芯。',
    iconPath: 'circularity',
  },
  {
    id: 'cylindricity',
    nameZh: '圆柱度',
    nameEn: 'Cylindricity',
    category: 'form',
    categoryZh: '形状公差',
    symbol: '⌭',
    datumRequirement: '无需基准',
    toleranceZone: '半径差为公差值 t 的两同轴圆柱面之间的区域',
    definition: '对圆柱面各项形状误差（圆度、素线直线度、轴线直线度等）的综合控制要求。',
    application: '精密主轴外径、柴油机柱塞偶件、精密测量针轴。',
    iconPath: 'cylindricity',
  },

  // 2. 轮廓公差 (Profile Tolerances) - 2种，可有可无基准
  {
    id: 'profile_line',
    nameZh: '线轮廓度',
    nameEn: 'Profile of a Line',
    category: 'profile',
    categoryZh: '轮廓公差',
    symbol: '⌒',
    datumRequirement: '有或无基准(可选)',
    toleranceZone: '包络一系列直径为公差值 t 的圆的两包络线之间的区域',
    definition: '限制平面或截面上任意非圆曲线实际轮廓对理想轮廓变动量的一项指标。',
    application: '凸轮轮廓曲线、飞机叶片截面翼型、齿轮渐开线齿形轮廓。',
    iconPath: 'profile_line',
  },
  {
    id: 'profile_surface',
    nameZh: '面轮廓度',
    nameEn: 'Profile of a Surface',
    category: 'profile',
    categoryZh: '轮廓公差',
    symbol: '⌓',
    datumRequirement: '有或无基准(可选)',
    toleranceZone: '包络一系列直径为公差值 t 的球的两包络面之间的区域',
    definition: '限制三维复杂曲面实际轮廓对理想理论曲面变动量的一项指标。',
    application: '汽车冲压外覆盖件型面、精密叶轮叶片曲面、模具曲面型腔。',
    iconPath: 'profile_surface',
  },

  // 3. 定向公差 (Orientation Tolerances) - 3种，必须有基准
  {
    id: 'parallelism',
    nameZh: '平行度',
    nameEn: 'Parallelism',
    category: 'orientation',
    categoryZh: '定向公差',
    symbol: '∥',
    datumRequirement: '必须有基准',
    toleranceZone: '距离为公差值 t 且平行于基准的两平行平面或圆柱面内的区域',
    definition: '控制被测要素（线或面）相对于基准要素保持理论上互相平行的准确程度。',
    application: '机床双导轨导向面、滑块上下滑动面、减速器平行齿轮输入输出轴心线。',
    iconPath: 'parallelism',
  },
  {
    id: 'perpendicularity',
    nameZh: '垂直度',
    nameEn: 'Perpendicularity',
    category: 'orientation',
    categoryZh: '定向公差',
    symbol: '⊥',
    datumRequirement: '必须有基准',
    toleranceZone: '距离为公差值 t 且垂直于基准平面/轴线的两平行面或圆柱面区域',
    definition: '控制被测要素相对于基准保持 90° 理论正交关系的准确程度。',
    application: '立柱对底座底面的垂直安装面、轴端法兰面与轴心线的正交性、销孔轴心与端面。',
    iconPath: 'perpendicularity',
  },
  {
    id: 'angularity',
    nameZh: '倾斜度 / 角度',
    nameEn: 'Angularity',
    category: 'orientation',
    categoryZh: '定向公差',
    symbol: '∠',
    datumRequirement: '必须有基准',
    toleranceZone: '与基准成理论正确角度、间距为公差值 t 的两平行平面/圆柱面区域',
    definition: '控制被测要素相对于基准保持除 90° 以外任意理论设计角度倾斜的准确程度。',
    application: '燕尾导轨斜面夹角、斜齿轮端面过渡倒角斜面、斜楔机构工作面。',
    iconPath: 'angularity',
  },

  // 4. 定位公差 (Location Tolerances) - 3种
  {
    id: 'position',
    nameZh: '位置度',
    nameEn: 'Position',
    category: 'location',
    categoryZh: '定位公差',
    symbol: '⌖',
    datumRequirement: '必须有基准',
    toleranceZone: '以理论正确位置为中心，直径为公差值 t 的圆、球或间距为 t 的平行面',
    definition: '限制点、线、面被测要素对其由理论正确尺寸确定之理想位置变动量的综合公差。',
    application: '多孔安装法兰螺栓孔分布中心、PCB引脚排孔、箱体多轴系轴孔坐标。',
    iconPath: 'position',
  },
  {
    id: 'coaxiality',
    nameZh: '同轴度 / 同心度',
    nameEn: 'Coaxiality / Concentricity',
    category: 'location',
    categoryZh: '定位公差',
    symbol: '◎',
    datumRequirement: '必须有基准',
    toleranceZone: '与基准轴线同轴，直径为公差值 t 的圆柱面内的区域',
    definition: '限制被测圆柱轴线对基准轴线偏离重合的一项定位指标，保证回转平衡与配合。',
    application: '阶梯轴各轴段轴心重合度、电机转子轴对两端轴承位中心、联轴器定位止口。',
    iconPath: 'coaxiality',
  },
  {
    id: 'symmetry',
    nameZh: '对称度',
    nameEn: 'Symmetry',
    category: 'location',
    categoryZh: '定位公差',
    symbol: '⌯',
    datumRequirement: '必须有基准',
    toleranceZone: '距离为公差值 t 且关于基准对称平面对称配置的两平行平面之间区域',
    definition: '限制被测中心要素（中心平面或中心线）偏离基准中心要素的定位公差。',
    application: '平键键槽相对轴心线的对称度、十字滑块滑槽中心对称、双向夹具定位槽。',
    iconPath: 'symmetry',
  },

  // 5. 跳动公差 (Runout Tolerances) - 2种，必须有基准
  {
    id: 'circular_runout',
    nameZh: '圆跳动',
    nameEn: 'Circular Runout',
    category: 'runout',
    categoryZh: '跳动公差',
    symbol: '↗',
    datumRequirement: '必须有基准',
    toleranceZone: '被测要素在垂直于基准轴线的测量截面内，半径差为 t 的同心圆或端面间距',
    definition: '被测实际要素绕基准轴线作无轴向移动回转一周时，指示表在任一固定截面内允许的最大变动量。',
    application: '高速旋转飞轮外缘径向圆跳动、皮带轮端面圆跳动、汽车刹车盘制动面。',
    iconPath: 'circular_runout',
  },
  {
    id: 'total_runout',
    nameZh: '全跳动',
    nameEn: 'Total Runout',
    category: 'runout',
    categoryZh: '跳动公差',
    symbol: '⇗',
    datumRequirement: '必须有基准',
    toleranceZone: '半径差为公差值 t 且与基准同轴的两圆柱面间区域，或垂直基准的两平行面',
    definition: '被测实际要素绕基准轴线连续旋转，同时指示表沿设计母线轴向平移时，整个表面允许的最大跳动量（综合反映形状和位置误差）。',
    application: '精密车床主轴锥孔全跳动、高速涡轮盘工作外径及两端面全跳动。',
    iconPath: 'total_runout',
  },
];
